In [19]:
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import FinanceDataReader as fdr
import csv

In [20]:
import requests
import requests as req
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import re
import time
import pickle

In [21]:
from html_table_parser import parser_functions
from html_table_parser import parser_functions as parser

In [22]:
from datetime import datetime, timedelta 
from dateutil.relativedelta import relativedelta
from datetime import datetime

In [51]:
pd.read_pickle('D:\B_Project5\기사\SK하이닉스.pickle')

,index,기업,날짜,제목,내용
0,0,SK하이닉스,연합뉴스2017.01.31.네이버뉴스,"개미들, 삼성전자·SK하이닉스 덕분에 살았다",주식시장에 단골 손실을 보는 투자자들인 개미들이 삼성전자와 SK하이닉스를 대거 ...
1,1,SK하이닉스,머니투데이2017.01.31.네이버뉴스,'투자 축소'가 올린 반도체 주가…SK하이닉스 '훨훨',[올해 1분기 영업이익 2조원 돌파 전망] SK하이닉스가 시가총액 40조원 돌파...
2,2,SK하이닉스,헤럴드경제2017.01.31.네이버뉴스,"SK하이닉스, 1분기 사상최대 영업익 전망… 또 ‘52주 신고가’",SK하이닉스가 올해 1분기 사상최대 영업이익 전망에 31일 52주 신고가를 또 ...
3,3,SK하이닉스,한국경제A11면 TOP2017.01.31.네이버뉴스,"SK하이닉스, SSD시장 '0.9%의 진격'",SDD 3D 낸드플래시 출시하며 반도체 영역 확장 [ 박재원 기자 ] SK하이닉...
4,4,SK하이닉스,시사위크2017.01.31.,"SK하이닉스, 도시바 '반도체 사업지분' 매각에 주목 왜?",일본 도시바의 반도체 사업부문 분리로 SK하이닉스의 행보에 관심이 집중된다. [...
...,...,...,...,...,...
2995,5,SK하이닉스,금융소비자뉴스2021.12.30.,SK하이닉스 인수 美인텔 낸드사업부 자회사 사명 '솔리다임',SK하이닉스가 인텔 SSD 사업을 운영할 미국 신설 자회사의 사명을 '솔리다임'...
2996,6,SK하이닉스,증권경제신문2021.12.30.,"SK하이닉스, 인텔 낸드 사업부 인수 1단계 절차 완료","SK하이닉스 CI SK하이닉스(000660, 대표 박정호·이석희)는 미국 인텔..."
2997,7,SK하이닉스,매일안전신문2021.12.30.,"SK하이닉스, 인텔 낸드사업부 1단계 인수완료…글로벌 일류 기술기업 도약발판",SK 하니닉스(사진=SK 하니닉스 홈페이지) SK하이닉스가 미국 인텔(Inte...
2998,8,SK하이닉스,인더뉴스2021.12.30.,"SK하이닉스, 자회사 ‘솔리다임’ 신설···인텔 낸드 사업부 인수 위한 ‘첫...","인텔에 70억 달러 지급예정 이석희 CEO, 솔리다임 의장 겸임 인더뉴스 이수민..."
2999,9,SK하이닉스,소비자가 만드는 신문2021.12.30.,"SK하이닉스, 인텔 낸드 사업부 1단계 인수 완료...""시너지 극대화로 글로벌 일...",SK하이닉스가 미국 인텔의 낸드플래시 사업부 인수 1단계 절차를 완료했다. SK...

In [41]:
li = ['더존비즈온', '흥구석유']

In [45]:
test_date = {'2017.01.01' : '2017.01.31', '2021.12.01' : '2021.12.31'}

In [46]:
cnt = 0
for p in li[:300]:
    df_oo = []
    for i,j in test_date.items():
        print(j, p)
        url = f'https://search.naver.com/search.naver?where=news&sm=tab_pge&query={p}&sort=0&photo=0&field=0&pd=3&ds={i}&de={j}&cluster_rank=34&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20170101to20170131,a:all&is_sug_officeid=1&start=1'
        res = requests.get(url)
        soup = BeautifulSoup(res.text, 'html.parser')
        page = soup.select('div.api_sc_page_wrap > div > div > a')[:5]
        
        for pa in page:
            news_dates = []
            news_title = []
            news_contents = []

            urls = f'https://search.naver.com/search.naver?where=news&sm=tab_pge&query={p}&sort=0&photo=0&field=0&pd=3&ds={i}&de={j}&cluster_rank=164&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20170101to20170131,a:all&is_sug_officeid=1&start={(int(pa.text) - 1) * 10 + 1}'
            print(urls)

            ress = requests.get(urls)

            soups = BeautifulSoup(ress.text, 'html.parser')

            date = soups.select('div.info_group')[:10]
            title = soups.select('a.news_tit')[:10]
            contents = soups.select('div.news_dsc')[:10]

            for m,k,l in zip(date, title, contents):
                news_dates.append(m.text)
#                 print(k.text)
                news_title.append(k.text)
                news_contents.append(l.text)

                globals()['df_'+str(p)] = pd.DataFrame({'기업' : p, '날짜' : news_dates, '제목' : news_title, '내용' : news_contents})
                
            
            df_oo.append(globals()['df_'+str(p)])
            
#     globals()['news_'+str(p)] = pd.concat([globals()['df_'+str(p)]])
    if page:
        df_news = pd.concat(df_oo)
        df_news.reset_index(inplace=True)
        df_news.to_pickle(f'D:\\B_Project5\\기사\\{p}.pickle')
            
#     cnt += 1
#     print(cnt, ',', p)
        
# df_news = pd.concat(df_oo)

2017.01.31 더존비즈온
https://search.naver.com/search.naver?where=news&sm=tab_pge&query=더존비즈온&sort=0&photo=0&field=0&pd=3&ds=2017.01.01&de=2017.01.31&cluster_rank=164&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20170101to20170131,a:all&is_sug_officeid=1&start=1
https://search.naver.com/search.naver?where=news&sm=tab_pge&query=더존비즈온&sort=0&photo=0&field=0&pd=3&ds=2017.01.01&de=2017.01.31&cluster_rank=164&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20170101to20170131,a:all&is_sug_officeid=1&start=11
https://search.naver.com/search.naver?where=news&sm=tab_pge&query=더존비즈온&sort=0&photo=0&field=0&pd=3&ds=2017.01.01&de=2017.01.31&cluster_rank=164&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20170101to20170131,a:all&is_sug_officeid=1&start=21
2021.12.31 더존비즈온
https://search.naver.com/search.naver?where=news&sm=tab_pge&query=더존비즈온&sort=0&photo=0&field=0&pd=3&ds=2021.12.01&de=2021.12.31&cluster_rank=164&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20170101to20170131,a:all&is_sug_officeid=1&start=1
https://search.naver.com/search.naver?where=news&sm=tab_pge&query=더존비즈온&sort=0&photo=0&field=0&pd=3&ds=2021.12.01&de=2021.12.31&cluster_rank=164&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20170101to20170131,a:all&is_sug_officeid=1&start=11
https://search.naver.com/search.naver?where=news&sm=tab_pge&query=더존비즈온&sort=0&photo=0&field=0&pd=3&ds=2021.12.01&de=2021.12.31&cluster_rank=164&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20170101to20170131,a:all&is_sug_officeid=1&start=21
https://search.naver.com/search.naver?where=news&sm=tab_pge&query=더존비즈온&sort=0&photo=0&field=0&pd=3&ds=2021.12.01&de=2021.12.31&cluster_rank=164&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20170101to20170131,a:all&is_sug_officeid=1&start=31
https://search.naver.com/search.naver?where=news&sm=tab_pge&query=더존비즈온&sort=0&photo=0&field=0&pd=3&ds=2021.12.01&de=2021.12.31&cluster_rank=164&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20170101to20170131,a:all&is_sug_officeid=1&start=41
2017.01.31 흥구석유
2021.12.31 흥구석유
https://search.naver.com/search.naver?where=news&sm=tab_pge&query=흥구석유&sort=0&photo=0&field=0&pd=3&ds=2021.12.01&de=2021.12.31&cluster_rank=164&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20170101to20170131,a:all&is_sug_officeid=1&start=1
https://search.naver.com/search.naver?where=news&sm=tab_pge&query=흥구석유&sort=0&photo=0&field=0&pd=3&ds=2021.12.01&de=2021.12.31&cluster_rank=164&mynews=0&office_type=0&office_section_code=0&news_office_checked=&nso=so:r,p:from20170101to20170131,a:all&is_sug_officeid=1&start=11