In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df_financial_statements = pd.read_csv('재무제표.csv')
df_financial_statements

,Unnamed: 0,매출액,영업이익,영업이익(발표기준),세전계속사업이익,당기순이익,당기순이익(지배),당기순이익(비지배),자산총계,부채총계,...,PER(배),BPS(원),PBR(배),현금DPS(원),현금배당수익률,현금배당성향(%),발행주식수(보통주),name,code,year
0,2017/12\n\t\t\t\t\t\t\t\t\t\n(IFRS연결),"2,395,754","536,450","536,450","561,960","421,867","413,446","8,422","3,017,521","872,607",...,9.40,"30,427",1.67,850,1.67,14.09,"6,454,924,700",삼성전자우,005935,2017
1,2018/12\n\t\t\t\t\t\t\t\t\t\n(IFRS연결),"2,437,714","588,867","588,867","611,600","443,449","438,909","4,540","3,393,572","916,041",...,6.42,"35,342",1.09,"1,416",3.66,21.92,"5,969,782,550",삼성전자우,005935,2018
2,2019/12\n\t\t\t\t\t\t\t\t\t\n(IFRS연결),"2,304,009","277,685","277,685","304,322","217,389","215,051","2,338","3,525,645","896,841",...,17.63,"37,528",1.49,"1,416",2.54,44.73,"5,969,782,550",삼성전자우,005935,2019
3,2020/12\n\t\t\t\t\t\t\t\t\t\n(IFRS연결),"2,368,070","359,939","359,939","363,451","264,078","260,908","3,170","3,782,357","1,022,877",...,21.09,"39,406",2.06,"2,994",3.70,77.95,"5,969,782,550",삼성전자우,005935,2020
4,2021/12\n\t\t\t\t\t\t\t\t\t\n(IFRS연결),"2,796,048","516,339","516,339","533,518","399,074","392,438","6,637","4,266,212","1,217,212",...,13.55,"43,611",1.80,"1,444",1.84,25.00,"5,969,782,550",삼성전자우,005935,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8630,2017/12\n\t\t\t\t\t\t\t\t\t\n(IFRS연결),"1,285",-31,-31,7,3,4,-1,803,417,...,168.16,"13,851",1.97,0,0.00,0.00,"2,811,871",Hankook,050540,2017
8631,2018/12\n\t\t\t\t\t\t\t\t\t\n(IFRS연결),"1,284",-93,-93,-187,-193,-188,-5,825,402,...,NaN,"11,018",2.77,0,0.00,0.00,"3,878,559",Hankook,050540,2018
8632,2019/12\n\t\t\t\t\t\t\t\t\t\n(IFRS연결),"1,211",-123,-123,-420,-370,-352,-18,899,779,...,NaN,"2,978",6.83,0,0.00,0.00,"3,878,559",Hankook,050540,2019
8633,2020/12\n\t\t\t\t\t\t\t\t\t\n(IFRS연결),"1,107",-7,-7,-52,-45,-40,-5,565,477,...,NaN,"1,954",1.44,0,0.00,0.00,"5,078,559",Hankook,050540,2020
8634,2021/12\n\t\t\t\t\t\t\t\t\t\n(IFRS연결),760,11,11,0,10,11,-1,356,256,...,12.63,"2,139",1.32,NaN,NaN,NaN,"5,118,559",Hankook,050540,2021

In [10]:
df_financial_statements = df_financial_statements.drop('Unnamed: 0', axis = 1)

In [11]:
df_financial_statements

,매출액,영업이익,영업이익(발표기준),세전계속사업이익,당기순이익,당기순이익(지배),당기순이익(비지배),자산총계,부채총계,자본총계,...,PER(배),BPS(원),PBR(배),현금DPS(원),현금배당수익률,현금배당성향(%),발행주식수(보통주),name,code,year
0,"2,395,754","536,450","536,450","561,960","421,867","413,446","8,422","3,017,521","872,607","2,144,914",...,9.40,"30,427",1.67,850,1.67,14.09,"6,454,924,700",삼성전자우,005935,2017
1,"2,437,714","588,867","588,867","611,600","443,449","438,909","4,540","3,393,572","916,041","2,477,532",...,6.42,"35,342",1.09,"1,416",3.66,21.92,"5,969,782,550",삼성전자우,005935,2018
2,"2,304,009","277,685","277,685","304,322","217,389","215,051","2,338","3,525,645","896,841","2,628,804",...,17.63,"37,528",1.49,"1,416",2.54,44.73,"5,969,782,550",삼성전자우,005935,2019
3,"2,368,070","359,939","359,939","363,451","264,078","260,908","3,170","3,782,357","1,022,877","2,759,480",...,21.09,"39,406",2.06,"2,994",3.70,77.95,"5,969,782,550",삼성전자우,005935,2020
4,"2,796,048","516,339","516,339","533,518","399,074","392,438","6,637","4,266,212","1,217,212","3,048,999",...,13.55,"43,611",1.80,"1,444",1.84,25.00,"5,969,782,550",삼성전자우,005935,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8630,"1,285",-31,-31,7,3,4,-1,803,417,386,...,168.16,"13,851",1.97,0,0.00,0.00,"2,811,871",Hankook,050540,2017
8631,"1,284",-93,-93,-187,-193,-188,-5,825,402,423,...,NaN,"11,018",2.77,0,0.00,0.00,"3,878,559",Hankook,050540,2018
8632,"1,211",-123,-123,-420,-370,-352,-18,899,779,120,...,NaN,"2,978",6.83,0,0.00,0.00,"3,878,559",Hankook,050540,2019
8633,"1,107",-7,-7,-52,-45,-40,-5,565,477,88,...,NaN,"1,954",1.44,0,0.00,0.00,"5,078,559",Hankook,050540,2020
8634,760,11,11,0,10,11,-1,356,256,100,...,12.63,"2,139",1.32,NaN,NaN,NaN,"5,118,559",Hankook,050540,2021

In [12]:
df_financial_statements.columns

Index(['매출액', '영업이익', '영업이익(발표기준)', '세전계속사업이익', '당기순이익', '당기순이익(지배)',
       '당기순이익(비지배)', '자산총계', '부채총계', '자본총계', '자본총계(지배)', '자본총계(비지배)', '자본금',
       '영업활동현금흐름', '투자활동현금흐름', '재무활동현금흐름', 'CAPEX', 'FCF', '이자발생부채', '영업이익률',
       '순이익률', 'ROE(%)', 'ROA(%)', '부채비율', '자본유보율', 'EPS(원)', 'PER(배)',
       'BPS(원)', 'PBR(배)', '현금DPS(원)', '현금배당수익률', '현금배당성향(%)', '발행주식수(보통주)',
       'name', 'code', 'year'],
      dtype='object')

In [13]:
df_financial_statements['CAPEX']

0       427,922
1       295,564
2       253,678
3       375,920
4       471,221
         ...
8630         57
8631         20
8632        183
8633          8
8634          2
Name: CAPEX, Length: 8635, dtype: object